services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: problemz
      PGDATA: /data/postgres
    volumes:
      - c:/tmp/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - graph-network
    restart: unless-stopped

networks:
  graph-network:

volumes:
  postgres: